ALTER TYPE "ActivityEntityType" ADD VALUE IF NOT EXISTS 'CUSTOMER';
ALTER TYPE "ActivityEntityType" ADD VALUE IF NOT EXISTS 'TICKET_CATEGORY';

ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'USER_STATUS_CHANGED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'USER_PASSWORD_RESET';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'USER_LOGGED_IN';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'USER_LOGGED_OUT';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_CREATED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_UPDATED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_DELETED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'TICKET_CATEGORY_CREATED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'TICKET_CATEGORY_UPDATED';
ALTER TYPE "ActivityLogAction" ADD VALUE IF NOT EXISTS 'TICKET_CATEGORY_DELETED';
